### ISSUE TITLE
Invariant Violation: requireNativeComponent: "KeyboardControllerView" was not found in the UIManager.

### ISSUE THREAD

**Issue by Wgga** [react-native-oh-library/react-native-keyboard-controller#14]
### 描述 / Description

Invariant Violation: requireNativeComponent: "KeyboardControllerView" was not found in the UIManager.

### 库版本 / Library version

1.12.7-0.0.3

### React Native OpenHarmony version

0.72.29

### 构建类型 / Build type

None

### 设备 / Device

Real device

### 已悉知 / Acknowledgements

Yes

**Comment by ganghongli** [comment]
这个问题应该是fabirc组件没有桥接成功，请按照指导文档https://gitee.com/react-native-oh-library/usage-docs/blob/master/zh-cn/react-native-keyboard-controller.md引入，还有问题可以联系我
