### ISSUE TITLE
啥时候能正常使用啊

### ISSUE THREAD

**Issue by TomWq** [react-native-oh-library/react-native-keyboard-controller#6]
文档地址都是 404 本地引入也会提示 No matching version found for react-native-keyboard-controller@1.12.17.    In most cases you or one of your dependencies are requesting     a package version that doesn't exist.

**Comment by ganghongli** [comment]
> 文档地址都是 404 本地引入也会提示 No matching version found for react-native-keyboard-controller@1.12.17. In most cases you or one of your dependencies are requesting a package version that doesn't exist.

已修复版本依赖错误问题，请使用新版本 https://github.com/react-native-oh-library/react-native-keyboard-controller/releases/tag/1.12.7-0.0.2

**Comment by TomWq** [comment]
感谢您这边还能回复， async-storage 那边根本没人搭理我  那个有错误 引入后  node_modules里的源码和 github 下的源码不一样   有几个引入都是错误的    也没人处理下  哎
